import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
            <Link href="/"><img src={`/images/logo.png`} className="logo"></img></Link>
            <Link href="/lean">학습과목</Link>
            <Link href="/data">자료실</Link>
            <Link href="/bbs">게시판</Link>
            <Link href="/notice">공지사항</Link>
            <Link href="/popular">인기과목</Link>
            <Link href="/list">방명록</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
