services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - sist_net
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    networks:
      - sist_net
    restart: always
    volumes:
      - ./conf/default.conf:/etc/ngins/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend

networks:
  sist_net:
    driver: bridge
    external: true # 기존 존재하는 Network를 사용