services:
  my_sql8: # 기존에 있는 image이고 아래 정의한 이름이 없으면 새로 다운받음
    image: my_sql8
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1111
    networks:
      - my-net1
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "3307:3306"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "8080:8080"
    depends_on:
      - my_sql8
    restart: always

networks:
  my-net1:
    driver: bridge